#!/bin/bash
#SBATCH -n 8 # Number of cores
#SBATCH --mem 16000 # 8GB solicitados.
#SBATCH -p mhigh # or mlow Partition to submit to master low prioriy queue
#SBATCH --gres gpu:1 # Para pedir Pascales MAX 8
#SBATCH -o logs/%x_%u_%j.out # File to which STDOUT will be written
#SBATCH -e logs/%x_%u_%j.err # File to which STDERR will be written
python fuse_training.py --model_name combined_loss_whisper --combined_loss --batch_size 128 --epochs 15
